permalink: '/:title'
markdown: kramdown
highlighter: pygments
paginate: 20
paginate_path: 'page/:num'
categories_path: categories.html
tags_path: tags.html
BASE_PATH: 'http://meliodus.github.io/uno-dbyll'
title: uno-dbyll
author:
  name: Ankan Biswas
  role: Jekyll Theme
  email: meliodus@tutanota.com
  github: meliodus
  twitter: talk2ankan
  facebook: talk2ankan
  googleplus: +AnkanBiswasWorkspace
  bio: 'Simple, clean, responsive and stylist theme for jekyll. '
  uno-dbyll: 'https://raw.githubusercontent.com/meliodus/uno-dbyll/gh-pages/uno-dbyll.png'
baseurl: ''
url: ''
